---
version: "3.9"
services:
  bed_socket:
    build: src/bed_socket
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "23778:23778"
    restart: unless-stopped
  controller_api:
    build: src/controller_api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - bed_socket
    ports:
      - "8080:80"
    restart: unless-stopped
  app_api:
    build: src/app_api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "80:80"
    restart: unless-stopped
  redis:
      image: redis:6
      ports:
        - "6379"
      restart: unless-stopped
