---
version: "3.9"
services:
  bed-socket:
    build: .
    entrypoint: bn-bed-socket
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "23778"
    restart: unless-stopped
  controller-api:
    build: .
    entrypoint: bn-controller-api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - bed-socket
    ports:
      - "8080:80"
    restart: unless-stopped
  app-api:
    build: .
    entrypoint: bn-app-api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "80"
    restart: unless-stopped
  redis:
      image: redis:6
      ports:
        - "6379"
      restart: unless-stopped
