FROM python:3.10.0-slim AS final

ARG USER="bnab"
ARG VENV="/venv"
ARG PIP="${VENV}/bin/pip"
ARG PYTHON="${VENV}/bin/python"

RUN apt update && apt -y full-upgrade && apt clean

RUN python -m venv ${VENV}

RUN ${PYTHON} -m pip install --upgrade pip

COPY dist dist
RUN ${PYTHON} -m pip install dist/*.whl

RUN groupadd -r ${USER} && useradd --no-log-init -m -r -g ${USER} ${USER}

USER ${USER}

ENV PATH="${VENV}/bin:$PATH"
