name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci_app-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Unit Test
        uses: docker/build-push-action@v2.5.0
        with:
          target: unittests
