name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Generate coverage report
        run: |
          pip install -r requirements-dev.txt
          tox
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: True
          fail_ci_if_error: True
