name: Release

on:
  push:
    tags: [ 'v*' ]

  workflow_dispatch:

jobs:
  release-pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Build
        run: |
          python -m pip install poetry==1.1.11
          poetry version ${{ github.ref_name }}
          poetry build
      - name: Generate coverage report
        run: |
          python -m pip install poetry==1.1.11
          poetry install --no-root
          poetry run tox
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: True
      - name: Publish
        run: |
          POETRY_PYPI_TOKEN_PYPI=${{ secrets.POETRY_PYPI_TOKEN_PYPI }} poetry publish

  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: trevorlauder/bn-adjustable-bed
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build
        uses: docker/build-push-action@v2.5.0
        with:
          build-args: |
            GIT_TAG=${{ github.ref_name }}
          target: final
          tags: ${{ steps.meta.outputs.tags }}
      - name: Save and Upload
        run: |
          docker save trevorlauder/bn-adjustable-bed > bn-adjustable-bed.tar
      - uses: actions/upload-artifact@v2
        with:
          name: bn-adjustable-bed
          path: bn-adjustable-bed.tar
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Generate coverage report
        run: |
          python -m pip install poetry==1.1.11
          poetry install --no-root
          poetry run tox
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: True

  release-push:
    needs: [release-build]
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: bn-adjustable-bed
      - name: Push to DockerHub
        run: |
          docker load -i bn-adjustable-bed.tar
          docker push trevorlauder/bn-adjustable-bed
