name: Release

on:
  push:
    tags: [ 'v*' ]

  workflow_dispatch:

jobs:
  release_build_app_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: trevorlauder/bn_adjustable_bed-app_api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build app_api
        uses: docker/build-push-action@v2.5.0
        with:
          context: src/app_api
          target: build
          tags: ${{ steps.meta.outputs.tags }}
      - name: Save and Upload app_api
        run: |
          docker save trevorlauder/bn_adjustable_bed-app_api > app_api.tar
      - uses: actions/upload-artifact@v2
        with:
          name: app_api
          path: app_api.tar
      - name: Unit Test app_api
        uses: docker/build-push-action@v2.5.0
        with:
          context: src/app_api
          target: unittests

  release_build_bed_socket:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: trevorlauder/bn_adjustable_bed-bed_socket
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build bed_socket
        uses: docker/build-push-action@v2.5.0
        with:
          context: src/bed_socket
          target: build
          tags: ${{ steps.meta.outputs.tags }}
      - name: Save and Upload app_api
        run: |
          docker save trevorlauder/bn_adjustable_bed-bed_socket > bed_socket.tar
      - uses: actions/upload-artifact@v2
        with:
          name: bed_socket
          path: bed_socket.tar

  release_build_controller_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: trevorlauder/bn_adjustable_bed-controller_api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build controller_api
        uses: docker/build-push-action@v2.5.0
        with:
          context: src/controller_api
          target: build
          tags: ${{ steps.meta.outputs.tags }}
      - name: Save and Upload controller_api
        run: |
          docker save trevorlauder/bn_adjustable_bed-controller_api > controller_api.tar
      - uses: actions/upload-artifact@v2
        with:
          name: controller_api
          path: controller_api.tar
      - name: Unit Test controller_api
        uses: docker/build-push-action@v2.5.0
        with:
          context: src/controller_api
          target: unittests

  release_push_app_api:
    needs: [release_build_app_api, release_build_bed_socket, release_build_controller_api]
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: app_api
      - name: Push to DockerHub
        run: |
          docker load -i app_api.tar
          docker push trevorlauder/bn_adjustable_bed-app_api

  release_push_bed_socket:
    needs: [release_build_app_api, release_build_bed_socket, release_build_controller_api]
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: bed_socket
      - name: Push to DockerHub
        run: |
          docker load -i bed_socket.tar
          docker push trevorlauder/bn_adjustable_bed-bed_socket

  release_push_controller_api:
    needs: [release_build_app_api, release_build_bed_socket, release_build_controller_api]
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: controller_api
      - name: Push to DockerHub
        run: |
          docker load -i controller_api.tar
          docker push trevorlauder/bn_adjustable_bed-controller_api
